<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'PHPQueue' => array($vendorDir . '/coderkungfu/php-queue/src'),
    'Clio' => array($vendorDir . '/clio/clio/src'),
);
