<?php return array(
    'root' => array(
        'name' => 'wikimedia/smash-pig',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'dc5f3dfe57fa443a71ee4b50878b8ddb4dc90923',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => false,
    ),
    'versions' => array(
        'amzn/login-and-pay-with-amazon-sdk-php' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => '0c923fe9926621bb8a39a22cecd1d2f33c75de30',
            'type' => 'library',
            'install_path' => __DIR__ . '/../amzn/login-and-pay-with-amazon-sdk-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'clio/clio' => array(
            'pretty_version' => '0.1.8',
            'version' => '0.1.8.0',
            'reference' => '6a9f600b73fa213e817d5c1e67a4641aecd156ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../clio/clio',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'coderkungfu/php-queue' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'cd29afd03a5b4b740ce6c50128f1e69723c54f72',
            'type' => 'library',
            'install_path' => __DIR__ . '/../coderkungfu/php-queue',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'corneltek/getoptionkit' => array(
            'pretty_version' => '2.7.2',
            'version' => '2.7.2.0',
            'reference' => 'aab2728de80175217cab0d7a4d078c3eb907e2c0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../corneltek/getoptionkit',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '2.9.3',
            'version' => '2.9.3.0',
            'reference' => 'a30bfe2e142720dfa990d0a7e573997f5d884215',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.9.1',
            'version' => '6.9.1.0',
            'reference' => '039de174cd9c17a8389754d3b877a2ed22743e18',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'predis/predis' => array(
            'pretty_version' => 'v1.1.10',
            'version' => '1.1.10.0',
            'reference' => 'a2fb02d738bedadcffdbb07efa3a5e7bd57f8d6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../predis/predis',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => 'd11b50ad223250cf17b86e38383413f5a6764bf8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0 || 2.0.0 || 3.0.0',
            ),
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.3',
            'version' => '2.5.3.0',
            'reference' => '80d075412b557d41002320b96a096ca65aa2c98d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'reference' => '3929d9fe8148d17819ad0178c748b8d339420709',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => 'ef4d7e442ca910c4764bce785146269b30cb5fc4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.29.0',
            'version' => '1.29.0.0',
            'reference' => '9773676c8a1bb1f8d4340a62efe641cf76eda7ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php54' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'reference' => '37285b1d5d13f37c8bee546d8d2ad0353460c4c7',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php55' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'reference' => 'c17452124a883900e1d73961f9075a638399c1a0',
            'type' => 'metapackage',
            'install_path' => NULL,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v5.4.39',
            'version' => '5.4.39.0',
            'reference' => 'bc780e16879000f77a1022163c052f5323b5e640',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'wikimedia/smash-pig' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'dc5f3dfe57fa443a71ee4b50878b8ddb4dc90923',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
